# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3c9120b1d39683fe1ae862f6c260067bf2fc04effe9d2d8529b00627cd7f8d9876b234c6e90a4533f3e0f12a8dc0c847c90015dcdc8aa5a9a0cabd7f3b0b2e1

test:
  secret_key_base: a6f3e0433607d69fb72bf7f6c8deed939ac9568338610f1a6b8d2904220d1db300390ff25d5880674a17cb7a89f701fa9b71e768ecd64d4a7f49d9b388c83bf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
